-- CR-044: 创建车辆设备证书表
-- 用于存储产线TBOX设备证书首次签发与车辆绑定信息

CREATE TABLE IF NOT EXISTS `tb_veh_certificate` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `request_id` varchar(64) NOT NULL COMMENT 'MES/OAPI业务请求幂等键',
  `pki_request_id` varchar(64) DEFAULT NULL COMMENT 'framework/PKI返回的申请编号',
  `cert_sn` varchar(128) DEFAULT NULL COMMENT 'PKI证书序列号',
  `vin` varchar(20) NOT NULL COMMENT '签发时车辆VIN快照',
  `binding_id` bigint NOT NULL COMMENT '签发时active vehicle_part.id',
  `part_id` bigint NOT NULL COMMENT '设备物理实例，关联part_info.id',
  `device_category` varchar(32) NOT NULL DEFAULT 'TBOX' COMMENT '设备类别，本期TBOX，预留其他ECU',
  `device_sn` varchar(64) NOT NULL COMMENT '证书CN对应的稳定设备身份/芯片UID',
  `certificate_profile` varchar(64) NOT NULL COMMENT '受治理证书模板，如TBOX_TSP_CLIENT',
  `csr_fingerprint` varchar(128) DEFAULT NULL COMMENT 'CSR SHA-256指纹',
  `subject` varchar(512) DEFAULT NULL COMMENT 'X.509 Subject',
  `issuer` varchar(512) DEFAULT NULL COMMENT 'X.509 Issuer',
  `certificate_fingerprint` varchar(128) DEFAULT NULL COMMENT '证书SHA-256指纹',
  `not_before` datetime DEFAULT NULL COMMENT '证书有效期开始时间',
  `not_after` datetime DEFAULT NULL COMMENT '证书有效期结束时间',
  `cert_status` varchar(32) NOT NULL DEFAULT 'REQUESTED' COMMENT '证书状态',
  `issued_at` datetime DEFAULT NULL COMMENT '签发时间',
  `confirmed_at` datetime DEFAULT NULL COMMENT '安装确认时间',
  `fail_reason` varchar(512) DEFAULT NULL COMMENT '最近失败原因',
  `source_system` varchar(32) DEFAULT NULL COMMENT '来源系统',
  `facility_no` varchar(32) DEFAULT NULL COMMENT '工厂编号',
  `line_code` varchar(32) DEFAULT NULL COMMENT '产线代码',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_by` varchar(64) DEFAULT NULL COMMENT '修改者',
  `row_version` int DEFAULT '1' COMMENT '记录版本',
  `row_valid` tinyint DEFAULT '1' COMMENT '记录是否有效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_id` (`request_id`),
  UNIQUE KEY `uk_cert_sn` (`cert_sn`),
  UNIQUE KEY `uk_pki_request_id` (`pki_request_id`),
  UNIQUE KEY `uk_device_profile_csr` (`device_sn`, `certificate_profile`, `csr_fingerprint`),
  KEY `idx_vin_status` (`vin`, `cert_status`),
  KEY `idx_device_sn_status` (`device_sn`, `cert_status`),
  KEY `idx_updated_at` (`modify_time`),
  KEY `idx_binding_id` (`binding_id`),
  KEY `idx_part_id` (`part_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆设备证书表';
