-- VMD-DSN-CR-056: 新建零件导入后置处理重放主任务与逐项动作审计表
-- 与 part_import_data / part_info / vehicle_part 分离，支撑零件导入后置处理人工重放（US-062）
-- 主任务记录一次完整重放；动作明细按 (replay_id, part_code, sn, action_type) 唯一，动作级幂等
CREATE TABLE `tb_part_import_postprocess_replay` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `replay_id` varchar(64) NOT NULL COMMENT '重放请求ID（幂等键）',
  `part_import_data_id` bigint NOT NULL COMMENT '关联的零件导入数据ID',
  `batch_num` varchar(64) NOT NULL COMMENT '原导入批次号',
  `operator_id` varchar(64) NOT NULL COMMENT '操作人ID',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `reason` varchar(500) DEFAULT NULL COMMENT '重放原因',
  `scope` varchar(500) DEFAULT NULL COMMENT '动作范围：逗号分隔的动作类型子集，空表示全部适用动作',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING/RUNNING/PARTIAL_SUCCESS/SUCCESS/FAILED',
  `total_item_count` int NOT NULL DEFAULT 0 COMMENT '候选实例总数',
  `total_action_count` int NOT NULL DEFAULT 0 COMMENT '规划动作总数',
  `queued_count` int NOT NULL DEFAULT 0 COMMENT '已入Outbox事件动作数',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功动作数',
  `skipped_count` int NOT NULL DEFAULT 0 COMMENT '跳过动作数',
  `failure_count` int NOT NULL DEFAULT 0 COMMENT '失败动作数',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_by` varchar(64) DEFAULT NULL COMMENT '修改人',
  `row_version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `row_valid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '逻辑删除标志：0-已删除，1-有效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_replay_id` (`replay_id`),
  KEY `idx_part_import_data_id` (`part_import_data_id`),
  KEY `idx_batch_num` (`batch_num`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='零件导入后置处理重放主任务表';

CREATE TABLE `tb_part_import_postprocess_replay_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `replay_id` varchar(64) NOT NULL COMMENT '关联重放任务ID',
  `part_code` varchar(64) NOT NULL COMMENT '零件编码',
  `sn` varchar(128) NOT NULL COMMENT '零件序列号',
  `action_type` varchar(32) NOT NULL COMMENT '动作类型：PART_INBOUND_EVENT/TSP_SYNC/OTA_SYNC/IDK_SYNC/BINDING_FACT_EVENT/SECURITY_PRESET',
  `idempotency_key` varchar(255) DEFAULT NULL COMMENT '动作幂等键（同步联动=replayId+partCode+sn+actionType；安全预置=(partCode,sn,constantType)）',
  `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '动作状态：PENDING/RUNNING/QUEUED/SUCCESS/SKIPPED/FAILED_RETRYABLE/FAILED_FINAL',
  `attempt_count` int NOT NULL DEFAULT 0 COMMENT '尝试次数',
  `event_id` varchar(64) DEFAULT NULL COMMENT '事件动作生成的事件ID',
  `outbox_id` bigint DEFAULT NULL COMMENT '事件动作关联的Outbox记录ID',
  `error_code` varchar(16) DEFAULT NULL COMMENT '错误码（下游既有业务异常保留原码）',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '错误信息（截断）',
  `skip_reason` varchar(255) DEFAULT NULL COMMENT '跳过原因（SKIPPED时记录）',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `modify_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `modify_by` varchar(64) DEFAULT NULL COMMENT '修改人',
  `row_version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `row_valid` tinyint(1) NOT NULL DEFAULT 1 COMMENT '逻辑删除标志：0-已删除，1-有效',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_replay_item` (`replay_id`, `part_code`, `sn`, `action_type`),
  KEY `idx_replay_id_status` (`replay_id`, `status`),
  KEY `idx_part_code_sn` (`part_code`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='零件导入后置处理重放动作明细表';
